const AuthErrors = {
    "auth/claims-too-large": "Le rivendicazioni superano la dimensione massima consentita.",
    "auth/email-already-exists": "L'email inserita è già associata a un altro account.",
    "auth/email-already-in-use": "L'email inserita è già associata a un altro account.",
    "auth/id-token-expired": "Il token ID è scaduto.",
    "auth/id-token-revoked": "Il token ID è stato revocato.",
    "auth/insufficient-permission": "Permessi insufficienti per eseguire questa operazione.",
    "auth/internal-error": "Errore interno del server. Riprova più tardi.",
    "auth/invalid-argument": "Argomento non valido fornito per l'operazione.",
    "auth/invalid-claims": "Attributi di rivendicazione personalizzati non validi.",
    "auth/invalid-continue-uri": "L'URL fornito non è valido.",
    "auth/invalid-creation-time": "La data di creazione non è valida.",
    "auth/invalid-credential": "Email o Password errate",
    "auth/invalid-disabled-field": "Il valore fornito per il campo disabilitato non è valido.",
    "auth/invalid-display-name": "Il nome visualizzato fornito non è valido.",
    "auth/invalid-dynamic-link-domain": "Il dominio del link dinamico non è configurato correttamente.",
    "auth/invalid-email": "L'indirizzo email fornito non è valido.",
    "auth/invalid-email-verified": "Il valore per la verifica email non è valido.",
    "auth/invalid-hash-algorithm": "Algoritmo di hashing non valido.",
    "auth/invalid-hash-block-size": "Dimensione del blocco hash non valida.",
    "auth/invalid-hash-derived-key-length": "Lunghezza della chiave derivata dall'hash non valida.",
    "auth/invalid-hash-key": "La chiave hash fornita non è valida.",
    "auth/invalid-hash-memory-cost": "Costo di memoria hash non valido.",
    "auth/invalid-hash-parallelization": "Parallelizzazione dell'hash non valida.",
    "auth/invalid-hash-rounds": "Numero di cicli hash non valido.",
    "auth/invalid-hash-salt-separator": "Il separatore di sale dell'hash non è valido.",
    "auth/invalid-id-token": "Il token ID fornito non è valido.",
    "auth/invalid-last-sign-in-time": "L'ora dell'ultimo accesso non è valida.",
    "auth/invalid-page-token": "Il token della pagina successiva non è valido.",
    "auth/invalid-password": "La password deve essere di almeno sei caratteri.",
    "auth/invalid-password-hash": "L'hash della password non è valido.",
    "auth/invalid-password-salt": "Il sale della password non è valido.",
    "auth/invalid-phone-number": "Il numero di telefono fornito non è valido.",
    "auth/invalid-photo-url": "L'URL della foto non è valido.",
    "auth/invalid-provider-data": "Dati del provider non validi.",
    "auth/invalid-provider-id": "ID del provider non valido.",
    "auth/invalid-oauth-responsetype": "Solo un responseType OAuth deve essere impostato su true.",
    "auth/invalid-session-cookie-duration": "La durata del cookie della sessione deve essere tra 5 minuti e 2 settimane.",
    "auth/invalid-uid": "L'UID fornito non è valido.",
    "auth/invalid-user-import": "Il record utente importato non è valido.",
    "auth/maximum-user-count-exceeded": "Superato il numero massimo di utenti consentiti.",
    "auth/missing-android-pkg-name": "Nome del pacchetto Android richiesto mancante.",
    "auth/missing-continue-uri": "URL continuo mancante.",
    "auth/missing-hash-algorithm": "Algoritmo di hashing mancante per l'importazione degli utenti.",
    "auth/missing-ios-bundle-id": "ID bundle iOS mancante.",
    "auth/missing-uid": "UID mancante per l'operazione richiesta.",
    "auth/missing-oauth-client-secret": "Il client secret OAuth è necessario per il flusso OIDC.",
    "auth/operation-not-allowed": "Il provider di accesso è disabilitato per questo progetto.",
    "auth/phone-number-already-exists": "Il numero di telefono è già associato a un altro account.",
    "auth/project-not-found": "Progetto Firebase non trovato.",
    "auth/reserved-claims": "Una o più rivendicazioni personalizzate fornite sono riservate.",
    "auth/session-cookie-expired": "Il cookie di sessione è scaduto.",
    "auth/session-cookie-revoked": "Il cookie di sessione è stato revocato.",
    "auth/too-many-requests": "Troppe richieste. Riprova più tardi.",
    "auth/uid-already-exists": "L'UID fornito è già in uso.",
    "auth/unauthorized-continue-uri": "Il dominio dell'URL continuo non è autorizzato.",
    "auth/user-not-found": "Utente non trovato con le credenziali fornite.",
  };
  
  export default AuthErrors;
  